apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Values.release.project_name }}-{{ .Values.release.platform }}
spec:
  encryptedData:
    twitter_access_secret: {{ .Values.release.twitter_access_secret }}
    twitter_access_token: {{ .Values.release.twitter_access_token }}
    twitter_key: {{ .Values.release.twitter_key }}
    twitter_secret: {{ .Values.release.twitter_secret }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Chart.Name }}-secret
      namespace: {{ .Values.release.project_name }}-{{ .Values.release.platform }}

