apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Values.release.project_name }}-{{ .Values.release.platform }}
spec:
  encryptedData:
    salesforce_clientId: {{ .Values.release.salesforce_clientId }}
    salesforce_secret: {{ .Values.release.salesforce_secret }}
    salesforce_refresh_token: {{ .Values.release.salesforce_refresh_token }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Chart.Name }}-secret
      namespace: {{ .Values.release.project_name }}-{{ .Values.release.platform }}

